Post endpoints
Deihast/DiscordBot-project-Vsevolod pull request #2
Opened 2022-07-21 21:45 UTC by Deihast

2022-08-17 08:59 UTC, Deihast commented
Выпилено

2022-08-18 06:10 UTC, BillyAleks requested changes
Посмотри комментарии и поменяй таргет бренч на develop

2022-08-18 06:10 UTC, BillyAleks commented on .gitignore
> +/src/config
Думаю этот конфиг не стоит выносить в гитигнор.
Он для develop окружения. То есть на следующих этапах stage или production это будет другой конфиг. Те поля, в которых твои личные данные ты можешь оставить пустыми. Но тот кто запустит твой проект должен понимать, почему запуск проекта ломается от импорта несуществующего файла.
Либо в Readme нужно оставить инструкции по его созданию и местоположению

2022-08-18 06:10 UTC, BillyAleks commented on src/routes/login.js
> +        res.status(200).json({ authKey: user.key, hashPass: user.password });
Никогда не отправляй пароль с бэка. Снаружи системы он не пригодится, а попасть не в те руки он может.

2022-08-18 06:10 UTC, BillyAleks commented on src/routes/newprofile.js
> +class CreateProfile {
Лучше вынести класс отдельно. В роутах должна быть логика исключительно роутинга.

2022-08-18 06:10 UTC, BillyAleks commented on src/routes/newprofile.js
> +
Новая строка не нужна

2022-08-18 06:10 UTC, BillyAleks commented on src/routes/register.js
> +class AuthorizationService {
Аналогично, сервис лучше положить отдельно.

2022-08-18 06:10 UTC, BillyAleks commented on src/routes/register.js
> +
Новая линия лишняя

2022-08-18 06:10 UTC, BillyAleks commented on src/routes/register.js
> +
Новая линия лишняя

2022-08-18 07:55 UTC, merged